useIstio: true
useHtttps: true
domainName: null
certIssuer: letsencrypt
paths:
  - path: /cms
    service:
      name: cms
      port: 80
  - path: /store
    service:
      name: store
      port: 80
  - path: /products
    service:
      name: products
      port: 80
