{{- define "json-products.name" -}}
  {{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "json-products.chart" -}}
  {{- printf "%s-%s" .Chart.Name (.Chart.Version | replace "+" "_" ) -}}
{{- end -}}

{{- define "json-products.image" -}}
  {{- printf "%s:%s" .repository .tag -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "json-products.name" . }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ include "json-products.name" . }}
    app.kubernetes.io/component: {{ .Values.group }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "json-products.chart" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "json-products.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "json-products.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - image: {{ include "json-products.image" .Values.image }}
          imagePullPolicy: .Values.image.pullPolicy
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{ toYaml .Values.imagePullSecrets }}
          {{- end }}
          env:
            - name: PRODUCTS_FILE
              value: /etc/secrets/products/products.json
            - name: PORT
              value: "80"
          {{- if .Values.resources }}
          resources:
            {{ toYaml .Values.resources }}
          {{- end }}
          volumeMounts:
            - name: products-volume
              mountPath: /etc/secrets/products
              readOnly: true
      ports:
        - containerPort: 80
      volumes:
        - name: products-volume
          secret:
            secretName: {{ .Values.secrets.products.name }}
            items:
              - key: products
                path: products.json
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "json-products.name" . }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ include "json-products.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "json-products.chart" . }}
type: Opaque
data:
  {{ range $key, $value := .Values.secrets.products.data -}}
      {{ $key }}: {{ $value | toJson | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "json-products.name" . }}
  labels:
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/name: {{ include "json-products.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "json-products.chart" . }}
  spec:
    type: {{ .Values.service.type }}
    ports:
    - name: http
      port: {{ .Values.service.ports.main.port }}
      targetPort: 80
      protocol: TCP
