{{- if and .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    group: {{ .Values.group }}
    version: {{ .Values.version }}
type: Opaque
data:
  {{- if .Values.rootPassword }}
  mongodb-root-password: {{ .Values.rootPassword | b64enc }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodbPassword }}
  mongodb-password: {{ .Values.mongodbPassword | b64enc }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}